### ISSUE TITLE
The discovery doc update PRs have not been merged in 5 days

### ISSUE THREAD

**Issue by diegomarquezp** [googleapis/discovery-artifact-manager#10794]
[This query](https://github.com/googleapis/discovery-artifact-manager/pulls/yoshi-code-bot) shows 5 consecutive days without merging the PRs generated by update_disco. The jobs seem to be running well ([example](https://github.com/googleapis/discovery-artifact-manager/actions/runs/9831941396/job/27140032228)).

![image](https://github.com/googleapis/discovery-artifact-manager/assets/22083784/53f1e5dd-fd5a-4d5e-905f-ad56d598d4c1)

**Comment by chingor13** [comment]
This is intentional for the time being. This workload is being migrated.
