### ISSUE TITLE
Document how to regen gapic config for discogapic

### ISSUE THREAD

**Issue by yihanzhen** [googleapis/discovery-artifact-manager#122]
After https://github.com/googleapis/artman/pull/669 is done.

**Comment by vam-google** [comment]
Closing as obsolete. The gapic config yaml does not have to be generated manually anymore, it is part of bazel pipeline and is regenerated automatically each time before generating the gapic client: https://github.com/googleapis/discovery-artifact-manager/blob/master/gapic/google/compute/v1/BUILD.bazel#L11
