### ISSUE TITLE
In all compilechecks, compare declared variables to their doc counterparts

### ISSUE THREAD

**Issue by saicheems** [googleapis/discovery-artifact-manager#19]
In dynamic languages, compilechecks can't handle situations where a variable is named differently from its documentation.

For example:

```
object2 = 0
```

```
Params:
  object (int): Lorem ipsum dolor...
```

**Comment by vchudnov-g** [comment]
Can we accomplish this via overrides for now? Given priorities, I am less inclined to invest in a general purpose solution right now.

**Comment by saicheems** [comment]
Not really, it's a compilecheck issue where it's hard to figure out what variable corresponds to the documented name.

I think the only way to 100% solve this is to implement the mock strategy for testing.
