### ISSUE TITLE
When updating discovery cache, the revision check should be more loose

### ISSUE THREAD

**Issue by dazuma** [googleapis/discovery-artifact-manager#86]
Currently when the discovery cache is updated, the revision fields are checked. If the new document has an "older" revision than what is currently in the cache, the update is aborted.

However, we currently have multiple cases where our cached discovery doc has a revision, but the latest from the discovery service _has no revision field_. (Two examples are content v2 and bigquery v2). This is causing https://github.com/googleapis/discovery-artifact-manager/blob/master/src/main/common/updatedisco.go#L229 to think the "empty" revision is "older" than our cached version. We should relax the check to allow this case.

**Comment by saicheems** [comment]
Hanzhen, assigning you just so someone takes a look at this. I'm not sure who has ownership of this today. Seems fairly high priority, and not too hard a fix.
